export const headerIconNames = [
  "ArrowRight",
  "ChartColumn",
  "Blocks",
  "BookOpen",
  "Box",
  "BrainCircuit",
  "Cloud",
  "Code",
  "Cpu",
  "Database",
  "FileText",
  "Gauge",
  "Globe",
  "Headphones",
  "Heart",
  "CircleHelp",
  "Image",
  "Key",
  "Layers",
  "LayoutGrid",
  "Lock",
  "Mail",
  "MessageSquare",
  "Monitor",
  "Paintbrush",
  "Palette",
  "Puzzle",
  "Rocket",
  "Search",
  "Server",
  "Settings",
  "Shield",
  "ShieldCheck",
  "Smartphone",
  "Sparkles",
  "Star",
  "Terminal",
  "Users",
  "WandSparkles",
  "Zap",
] as const;

export type HeaderIconName = (typeof headerIconNames)[number];
